services:
  - type: web
    name: banterbox-discord-bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production