services:
  - type: web
    name: banterbox-discord-bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - client/**
        - server/**
        - shared/**
        - package.json
        - package-lock.json
        - tsconfig*.json
        - vite.config.ts
        - tailwind.config.ts
        - postcss.config.js